/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#0A2540",
          foreground: "#F9FAFB",
        },
        secondary: {
          DEFAULT: "#00D4AA",
          foreground: "#0A0E1A",
        },
        accent: {
          DEFAULT: "#F6A623",
          foreground: "#0A0E1A",
        },
        destructive: {
          DEFAULT: "#CE1126",
          foreground: "#F9FAFB",
        },
        muted: {
          DEFAULT: "#6B7280",
          foreground: "#9CA3AF",
        },
        popover: {
          DEFAULT: "#162032",
          foreground: "#F9FAFB",
        },
        card: {
          DEFAULT: "#111827",
          foreground: "#F9FAFB",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Custom design tokens
        ocean: "#0A2540",
        coral: "#F6A623",
        teal: "#00D4AA",
        danger: "#CE1126",
        warning: "#FFB020",
        "bg-dark": "#0A0E1A",
        "bg-card": "#111827",
        "bg-card-hover": "#1A2235",
        "bg-elevated": "#162032",
        "bg-input": "#0D1117",
        "text-primary": "#F9FAFB",
        "text-secondary": "#9CA3AF",
        "text-muted": "#6B7280",
        "text-accent": "#F6A623",
        "text-teal": "#00D4AA",
        "text-red": "#CE1126",
      },
      fontFamily: {
        inter: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        display: ['"Space Grotesk"', 'Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'SF Mono', 'Menlo', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "sm": "6px",
        "md": "10px",
        "lg": "16px",
        "xl": "24px",
        "full": "9999px",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "20px",
        "2xl": "24px",
        "3xl": "32px",
        "4xl": "48px",
        "18": "72px",
      },
      fontSize: {
        "display": ["28px", { lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.02em" }],
        "h1": ["24px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.01em" }],
        "h2": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "h3": ["17px", { lineHeight: "1.35", fontWeight: "600" }],
        "h4": ["15px", { lineHeight: "1.4", fontWeight: "600" }],
        "body": ["15px", { lineHeight: "1.6", fontWeight: "400", letterSpacing: "0.01em" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400", letterSpacing: "0.01em" }],
        "caption": ["11px", { lineHeight: "1.4", fontWeight: "500", letterSpacing: "0.02em" }],
        "badge": ["10px", { lineHeight: "1", fontWeight: "600", letterSpacing: "0.04em" }],
        "tab-label": ["10px", { lineHeight: "1.2", fontWeight: "500" }],
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: "0 2px 8px rgba(0,0,0,0.2)",
        "card-elevated": "0 8px 24px rgba(0,0,0,0.3)",
        "fab": "0 4px 16px rgba(246,166,35,0.3)",
        glow: "0 0 20px rgba(246,166,35,0.2)",
        "glow-teal": "0 0 20px rgba(0,212,170,0.2)",
      },
      maxWidth: {
        mobile: "430px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-40px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 5px rgba(246,166,35,0.3)" },
          "50%": { boxShadow: "0 0 20px rgba(246,166,35,0.6), 0 0 40px rgba(246,166,35,0.2)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-in": "fade-in 300ms cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-up": "slide-up 400ms cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-down": "slide-down 300ms cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "shimmer": "shimmer 1.5s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "spin-slow": "spin-slow 0.8s linear infinite",
        "float": "float 3s ease-in-out infinite",
      },
      transitionTimingFunction: {
        "ease-out-custom": "cubic-bezier(0.16, 1, 0.3, 1)",
        "ease-in-out-custom": "cubic-bezier(0.65, 0, 0.35, 1)",
        "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
