# Docker Desktop Factory Reset
# Run as Administrator
# Generated by AI assistant 2026-06-06

$ErrorActionPreference = 'SilentlyContinue'

Write-Host "=== Docker Desktop Factory Reset ===" -ForegroundColor Cyan
Write-Host ""

# 1. 停止所有 Docker 进程
Write-Host "[1/5] 停止 Docker 进程..." -ForegroundColor Yellow
Get-Process -Name "Docker Desktop","com.docker.*","dockerd","com.docker.proxy" -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep 2

# 2. 停止服务
Write-Host "[2/5] 停止 Docker 服务..." -ForegroundColor Yellow
Stop-Service com.docker.service -Force
Set-Service com.docker.service -StartupType Manual

# 3. 删除所有 Docker 数据/配置
Write-Host "[3/5] 删除 AppData/Docker..." -ForegroundColor Yellow
$paths = @(
    "$env:APPDATA\Docker",
    "$env:APPDATA\Docker Desktop",
    "$env:LOCALAPPDATA\Docker",
    "$env:LOCALAPPDATA\Docker Desktop",
    "$env:PROGRAMDATA\Docker",
    "$env:PROGRAMDATA\Docker Desktop",
    "$env:PROGRAMDATA\DockerDesktop",
    "$env:APPDATA\..\Local\Packages\Docker.DockerDesktop",
    "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Docker\Docker Desktop.lnk"
)
foreach ($p in $paths) {
    if (Test-Path $p) {
        Remove-Item $p -Recurse -Force
        Write-Host "  已删除: $p" -ForegroundColor DarkGray
    }
}

# 4. 清理 WSL 中的 docker-desktop-data 和 docker-desktop
Write-Host "[4/5] 注销 WSL 发行版..." -ForegroundColor Yellow
wsl --unregister docker-desktop-data 2>&1 | Out-Null
wsl --unregister docker-desktop 2>&1 | Out-Null
wsl --shutdown

# 5. 验证
Write-Host ""
Write-Host "[5/5] 验证清理结果..." -ForegroundColor Yellow
$remaining = @(
    "$env:APPDATA\Docker",
    "$env:LOCALAPPDATA\Docker"
)
$allClean = $true
foreach ($p in $remaining) {
    if (Test-Path $p) {
        Write-Host "  ⚠ 仍存在: $p" -ForegroundColor Red
        $allClean = $false
    }
}

if ($allClean) {
    Write-Host ""
    Write-Host "✓ 清理完成!请手动重启 Docker Desktop" -ForegroundColor Green
    Write-Host ""
    Write-Host "下一步:" -ForegroundColor Cyan
    Write-Host "  1. 启动 Docker Desktop (开始菜单)" -ForegroundColor White
    Write-Host "  2. 首次启动会要求 WSL 2 Ubuntu 发行版" -ForegroundColor White
    Write-Host "  3. 如果没有 Ubuntu,先运行: wsl --install -d Ubuntu" -ForegroundColor White
    Write-Host "  4. 重启电脑" -ForegroundColor White
} else {
    Write-Host ""
    Write-Host "⚠ 部分文件未删除,请手动检查" -ForegroundColor Red
}

Write-Host ""
Write-Host "按 Enter 退出..."
Read-Host
