# =============================================================================
#  PowerShell Profile - SMYweb3.0
#  Generated by: oh-my-posh setup at 2026-06-06
# =============================================================================

# --- oh-my-posh prompt -------------------------------------------------------
# oh-my-posh >= 28 requires PowerShell 7+ (PSReadLine 2.2+ key handler API).
# On PS 5.1 we keep the stock prompt but warn the user.
if ($PSVersionTable.PSVersion.Major -ge 7) {
    $ompTheme = "C:\Users\HUAWEI\Documents\PowerShell\omp-theme.json"
    if (Test-Path $ompTheme) {
        try {
            oh-my-posh init pwsh --config "$ompTheme" | Invoke-Expression
        } catch {
            Write-Warning "[profile] oh-my-posh init failed: $($_.Exception.Message)"
        }
    } else {
        Write-Warning "[profile] omp-theme.json not found at $ompTheme"
    }
}

# --- PSReadLine (history, syntax) -------------------------------------------
if ($Host.Name -eq "ConsoleHost" -and (Get-Module -ListAvailable -Name PSReadLine)) {
    Import-Module PSReadLine
    Set-PSReadLineOption -HistoryNoDuplicates -HistorySearchCursorMovesToEnd
    Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    Set-PSReadLineKeyHandler -Key "Ctrl+d" -Function DeleteCharOrExit
    if ($PSVersionTable.PSVersion.Major -ge 7) {
        Set-PSReadLineOption -PredictionSource History
    }
}

# --- Terminal icons for ls --------------------------------------------------
if (Get-Command terminal-icons -ErrorAction SilentlyContinue) {
    Import-Module terminal-icons
}

# --- zoxide (smarter cd) ----------------------------------------------------
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    Invoke-Expression "$(zoxide init pwsh)"
}

# --- Useful aliases ---------------------------------------------------------
Set-Alias -Name ll   -Value Get-ChildItem   -Option AllScope -Force
Set-Alias -Name la   -Value "ls -Force"     -Option AllScope -Force
Set-Alias -Name g    -Value git             -Option AllScope -Force
Set-Alias -Name gp   -Value "git push"      -Option AllScope -Force
Set-Alias -Name lg   -Value "lazygit"       -Option AllScope -Force -ErrorAction SilentlyContinue
Set-Alias -Name cgr  -Value "codegraph query"  -Option AllScope -Force
Set-Alias -Name cgs  -Value "codegraph status" -Option AllScope -Force

# --- MOTD (once per session) ------------------------------------------------
$motdTag = "omp-motd-shown-$PID"
if (-not (Get-Variable -Name $motdTag -Scope Global -ErrorAction SilentlyContinue)) {
    Set-Variable -Name $motdTag -Value $true -Scope Global
    Write-Host ""
    Write-Host "  \u26a1 SMYweb3.0 dev shell" -ForegroundColor Cyan
    Write-Host "  powershell ::  " -NoNewline -ForegroundColor DarkGray
    Write-Host "$($PSVersionTable.PSVersion)" -ForegroundColor Green
    Write-Host "  oh-my-posh  ::  " -NoNewline -ForegroundColor DarkGray
    $ompV = oh-my-posh --version 2>$null
    if ($PSVersionTable.PSVersion.Major -lt 7) {
        Write-Host "$ompV " -ForegroundColor DarkGray -NoNewline
        Write-Host "(PS 5.1 - install pwsh 7+ for full theme)" -ForegroundColor Yellow
    } else {
        Write-Host $ompV -ForegroundColor Green
    }
    Write-Host "  codegraph   ::  " -NoNewline -ForegroundColor DarkGray
    Write-Host (codegraph --version 2>$null) -ForegroundColor Green
    Write-Host ""
}
